apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "ed2ed474-563a-4a3e-ada7-742290c4a5b3"
  labels:
    azure.workload.identity/use: "true"
